import * as E from './engine.js?v=0.3';
import * as O from './opening.js?v=0.3';
const $=s=>document.querySelector(s),KEY='renjian-chronicles-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Z',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',book:'M12 5v16M3 3c4 0 7 0 9 2 2-2 5-2 9-2v16c-4 0-7 0-9 2-2-2-5-2-9-2V3Z',activity:'M3 12h4l3-8 4 16 3-8h4',moon:'M21 12.8A9 9 0 0 1 11.2 3 9 9 0 1 0 21 12.8Z',chat:'M21 11.5a8.5 8.5 0 0 1-8.5 8.5H3l2-5a8.5 8.5 0 1 1 16-3.5Z',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M16 3a4 4 0 0 1 0 8M22 21v-2a4 4 0 0 0-3-3.8M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',music:'M9 18V5l12-2v13M9 18a3 3 0 1 1-3-3c2 0 3 1 3 3ZM21 16a3 3 0 1 1-3-3c2 0 3 1 3 3Z',briefcase:'M16 21H4a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-4ZM8 5V3h8v2M2 11a24 24 0 0 0 20 0M10 12h4',wallet:'M21 8V5a2 2 0 0 0-2-2H5a3 3 0 0 0 0 6h16v12H5a3 3 0 0 1-3-3V6M21 13h-5v4h5',flower:'M12 12c-9-8-14 4-3 4-3 11 10 11 6 0 11 0 6-12-3-4ZM12 12c-5-11 5-14 5-5 0 3-3 4-5 5Z',home:'m3 10 9-7 9 7v11H3V10ZM9 21v-8h6v8',tree:'M12 3v7M5 21v-7h14v7M12 14v7M8 3h8v5H8V3Z',calendar:'M4 5h16v16H4V5ZM8 3v4M16 3v4M4 11h16M8 15h2M14 15h2',settings:'M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8ZM12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2',check:'m5 12 4 4L19 6',plus:'M12 5v14M5 12h14',close:'m6 6 12 12M6 18 18 6',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 7v5l3 2',gift:'M3 8h18v4H3V8ZM5 12v9h14v-9M12 8v13M12 8C3 9 4 1 8 3l4 5Zm0 0c9 1 8-7 4-5l-4 5Z',download:'M12 3v12m-5-5 5 5 5-5M3 16v5h18v-5',upload:'M12 16V4m-5 5 5-5 5 5M3 16v5h18v-5',chevron:'m9 5 7 7-7 7',award:'M8 14 6 22l6-3 6 3-2-8M18 8a6 6 0 1 1-12 0 6 6 0 0 1 12 0Z'};
const icon=(name,cl='')=>`<svg class="icon ${cl}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.spark}"/></svg>`;
const NAV=[['life','home','生活'],['people','users','人物'],['growth','activity','成长'],['assets','wallet','资产'],['family','tree','家族']];
let db={current:0,slots:[null,null,null]},saveError='',view='life',peopleFilter='全部',modalKind='',selectedPerson=null,toastTimer;
try{const raw=localStorage.getItem(KEY);if(raw){const data=JSON.parse(raw);if(!data||!Array.isArray(data.slots)||data.slots.length!==3||!Number.isInteger(data.current)||data.current<0||data.current>2)throw Error();data.slots.forEach(s=>{if(s)O.validateOpening(E.validateGame(s.game))});db=data;}}catch{saveError='无法读取原存档。请导入备份恢复；原数据尚未覆盖。';}
let screen='menu';
if(!db.slots[db.current]&&db.slots.some(Boolean))db.current=db.slots.findIndex(Boolean);
let game=db.slots[db.current]?.game||null;let protectSave=!!saveError;
function save(){if(protectSave||!game)return;db.slots[db.current]={game,updated:Date.now()};try{localStorage.setItem(KEY,JSON.stringify(db));saveError='';}catch{saveError='设备存储未成功，请在存档中导出备份。';}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3000);}
function p(){return E.active(game)}
function ageText(person=p()){const months=game.time-person.born;return `${Math.floor(months/12)}岁${months%12?` ${months%12}个月`:''}`;}
function avatar(person=p(),size=''){return `<span class="avatar ${size} ${person.gender==='女'?'rose':''}">${esc(person.name.slice(-1))}${person.alive?'':'<span class="deceased">忆</span>'}</span>`;}
const signed=n=>(n>0?'+':'')+n;
const btn=(label,act,cls='secondary',extra='')=>`<button class="${cls}" data-act="${act}" ${extra}>${label}</button>`;
function meter(label,value,tone='blue'){return `<div class="meter"><div><span>${label}</span><strong>${Math.round(value)}<small>/100</small></strong></div><div class="bar ${tone}" role="meter" aria-label="${label}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(value)}"><i style="width:${E.clamp(value)}%"></i></div></div>`;}
function header(){return `<header class="topbar"><a class="brand" href="#" data-act="menu" aria-label="返回主菜单"><span class="brand-mark">续</span><span>人间续章<small>LIFE, ONE CHAPTER AT A TIME</small></span></a><div class="top-actions"><button class="menu-return" data-act="menu">主菜单</button><span class="save-status">${saveError?'存档需备份':'已自动保存'}</span><button class="icon-button" data-act="settings" aria-label="存档与设置">${icon('settings')}</button></div></header>`;}
function profile(){const x=p(),a=E.age(game);return `<section class="profile card"><div class="eyebrow"><span>第 ${x.generation} 代 · ${esc(x.name[0])}氏家族</span><span class="pill">${esc(E.stage(game))}</span></div><div class="identity">${avatar(x,'large')}<div><h1>${esc(x.name)}</h1><p>${esc(x.gender)} · ${esc(game.origin)}</p></div><div class="age"><b>${a}</b><span>岁 <strong>${(game.time-x.born)%12}</strong> 个月</span></div></div><div class="profile-stats">${O.CORE.map(([k,label,tone])=>meter(label,x[k]??50,tone)).join('')}</div>${x.startTraits?.length?`<div class="core-traits">${x.startTraits.map(id=>`<span>${esc(O.TRAITS.find(t=>t.id===id)?.name)}</span>`).join('')}</div>`:''}<div class="profile-foot"><span>${icon('home')}${esc(E.residence(game))}</span><span>${icon('wallet')}¥${E.money(x.savings)}</span></div></section>`;}
function nav(){return `<nav class="navigation" aria-label="游戏页面">${NAV.map(([id,ic,t])=>`<button data-act="nav" data-id="${id}" class="${view===id?'active':''}" ${view===id?'aria-current="page"':''}>${icon(ic)}<span>${t}</span></button>`).join('')}</nav>`;}
function pageTitle(eyebrow,title,right=''){return `<div class="section-heading"><div><div class="eyebrow">${eyebrow}</div><h2>${title}</h2></div>${right}</div>`;}
function life(){const x=p(),a=E.age(game),available=E.actions(game),full=game.plan.length===4;return `${pageTitle(`${['冬','冬','春','春','春','夏','夏','夏','秋','秋','秋','冬'][game.time%12]}日 · ${game.time%12+1}月`,'这个月，想做些什么？',`<span class="round-icon">${icon('calendar')}</span>`)}${guidePanel()}${game.time===0?`<div class="birth-note"><span class="round-icon">${icon('spark')}</span><div><strong>你好，${esc(x.name)}。</strong><p>${esc(game.logs[0].text)}</p></div></div>`:''}${game.ended?`<section class="card end-card">${icon('book')}<h3>这一生，已成故事</h3><p>去家族档案看看留下的记忆，选择一位家人续写下一章。</p>${btn('查看家族与接班','nav','primary','data-id="family"')}</section>`:`<section class="card planning"><div class="row"><h3>本月安排</h3><span class="muted"><b class="blue">${game.plan.length}</b> / 4 次行动</span></div><div class="plan-slots">${Array.from({length:4},(_,i)=>{const ac=available.find(z=>z.id===game.plan[i]);return game.plan[i]?`<button class="plan-slot filled" data-act="remove-plan" data-id="${i}" aria-label="移除${esc(ac?.name||'人物互动')}">${icon(ac?.icon||'chat')}<span>${esc(ac?.name||'人物互动')}</span>${icon('close','tiny')}</button>`:`<div class="plan-slot empty"><span>${String(i+1).padStart(2,'0')}</span><small>待安排</small></div>`}).join('')}</div><p class="hint">${a<3?'每一次探索与回应，都是成长的一小步。':a<18?'上学会照常进行，把时间分给你在意的事。':x.job?'本职工作照常进行，额外投入会影响表现。':'每次行动占用一格时间，可以重复安排。'}</p></section><div class="actions-grid">${available.map(ac=>{const count=game.plan.filter(id=>id===ac.id).length;return `<button class="action-card ${count?'chosen':''}" data-act="plan" data-id="${ac.id}" ${full?'disabled':''}><span class="action-icon ${ac.icon}">${icon(ac.icon)}</span><span class="action-copy"><strong>${esc(ac.name)}</strong><small>${esc(ac.desc)}</small><em>${esc(ac.place)}${ac.effect.energy<0?` · 精力 ${ac.effect.energy}`:''}</em></span><span class="action-add">${count?count:icon('plus')}</span></button>`}).join('')}</div><div class="month-control"><span>${full?'安排好了，让生活向前一步':'还可以安排 '+(4-game.plan.length)+' 次行动'}</span><button class="primary advance" data-act="advance" ${full?'':'disabled'}>${icon('calendar')}度过这个月</button></div>`}${game.summary?.deltas?`<section class="card month-summary"><div class="row"><h3>刚刚过去的一个月</h3><span class="tag">${ageText()}</span></div><div class="changes">${Object.entries({ability:'智力',luck:'运气',appearance:'颜值',mood:'心情'}).map(([k,label])=>`<span>${label}<b class="${(game.summary.deltas[k]??0)>=0?'positive':'negative'}">${k==='savings'?'¥':''}${signed(game.summary.deltas[k]??0)}</b></span>`).join('')}</div>${game.summary.details.length?`<p>${esc(game.summary.details.join('；'))}</p>`:''}</section>`:''}<div class="row timeline-title"><h3>生活的足迹</h3>${btn('查看成长记录','nav','text-button','data-id="growth"')}</div>${timeline(game.logs.filter(l=>l.person===x.id).slice(0,3))}`;}
function timeline(logs){if(!logs.length)return `<div class="empty-state">故事还在开始，下一次选择会留在这里。</div>`;return `<div class="timeline">${logs.map(l=>`<article class="timeline-item ${l.type==='milestone'?'milestone':''}"><div class="timeline-dot"></div><span class="meta">${l.age}岁${l.month?' '+l.month+'个月':''}${l.type==='milestone'?' · 人生印记':''}</span><h4>${esc(l.title)}</h4><p>${esc(l.text)}</p></article>`).join('')}</div>`;}
function people(){let list=game.people.filter(x=>x.id!==game.active&&x.alive);if(peopleFilter==='家人')list=list.filter(x=>x.family);if(peopleFilter==='朋友')list=list.filter(x=>!x.family);return `${pageTitle('人与人之间','有人，陪你走过一程',`<span class="count">${list.length} 人</span>`)}<div class="filter-tabs">${['全部','家人','朋友'].map(t=>btn(t,'filter',peopleFilter===t?'selected':'',`data-id="${t}"`)).join('')}</div><div class="people-grid">${list.map(q=>{const b=E.bond(game,game.active,q.id);return `<button class="person-card card" data-act="person" data-id="${q.id}">${avatar(q)}<div class="person-info"><div class="row"><h3>${esc(q.name)}</h3><span class="tag">${esc(E.relationship(game,q))}</span></div><p>${ageText(q)} · ${esc(q.trait)} · ${esc(q.job?.[0]||q.education)}</p><div class="relationship-meter"><span>亲密 ${Math.round(b.closeness)}</span><div class="bar rose"><i style="width:${b.closeness}%"></i></div></div>${b.memories.length?`<small class="memory-preview">${icon('chat')}${esc(b.memories[0].text)}</small>`:''}</div>${icon('chevron','person-chevron')}</button>`}).join('')||'<div class="card empty-state">还没有认识朋友。在生活页安排「结识朋友」，让新的故事发生。</div>'}</div><p class="footnote">重要的人会记住你们的共同经历。亲密与信任，在一次次相处中累积。</p>`;}
function growth(){const x=p();return `${pageTitle('每一步，都算数','长成自己的样子')}<div class="growth-top card"><div class="row"><span class="round-icon">${icon('award')}</span><div><span class="meta">当前人生阶段</span><h3>${esc(E.stage(game))}</h3></div><span class="tag">${esc(x.education)}</span></div><div class="growth-meters">${O.CORE.map(([k,label,tone])=>meter(label,x[k]??50,tone)).join('')}</div><p class="hint">智力影响学习和求职；运气影响成长际遇、求职与经营；颜值影响约会亲密收益；心情记录生活的感受。</p>${x.flags.university?`<p class="info-note">${esc(x.flags.university)} · 入学成绩 ${x.flags.examScore} / 750</p>`:''}<div class="trait-row">${(x.startTraits||[]).map(id=>`<span>${esc(O.TRAITS.find(t=>t.id===id)?.name)}</span>`).join('')}</div></div><div class="life-stages">${[[0,'出生'],[6,'入学'],[18,'成年'],[22,'社会'],[60,'退休']].map(([a,t])=>`<span class="${E.age(game)>=a?'reached':''}"><i></i>${t}<small>${a}岁</small></span>`).join('')}</div><div class="row timeline-title"><h3>人生印记</h3><span class="meta">${x.moments.length} 个重要时刻</span></div>${timeline(x.moments)}<details class="history"><summary>展开近期生活记录</summary>${timeline(game.logs.filter(l=>l.person===x.id).slice(0,60))}</details>`;}
function assets(){const x=p(),minor=E.age(game)<18;return `${pageTitle('把日子安顿下来','生活，有自己的底气')}<section class="wealth-card"><span>个人净资产</span><div class="wealth-number"><small>¥</small>${E.money(E.netWorth(x))}</div><div class="wealth-stats"><span>可用存款<b>¥${E.money(x.savings)}</b></span><span>待还债务<b>¥${E.money(x.debt)}</b></span></div></section><div class="finance-grid"><div class="card"><span class="meta">基础月收入</span><strong class="positive">+ ¥${E.money(E.income(game))}</strong><small>${minor?'尚未独立，家庭承担生活开销':E.age(game)>=60?'每月养老金':x.job?esc(x.job[0])+' · '+x.level+'级岗位':'暂无固定工作'}</small></div><div class="card"><span class="meta">每月生活支出</span><strong>¥${E.money(E.expense(game))}</strong><small>不含还款与临时开销</small></div></div>${minor?'<div class="info-note">目前由家人照顾生活，成年后可以独立买房、经营和布置住处。零用钱已经记入个人存款。</div>':''}<section class="card asset-section"><div class="row"><span class="round-icon">${icon('home')}</span><div class="flex"><h3>${esc(E.residence(game))}</h3><p>${x.homes?`${x.homes} 套住宅 · 每套估值 ¥600,000`:'一个落脚的地方，也是生活的起点。'}</p></div></div><div class="button-row">${btn('购房 · 首付 12万','asset','secondary',`data-id="buyHome" ${minor?'disabled':''}`)}${x.homes?btn('出售一套','asset','secondary','data-id="sellHome"'):''}${x.debt?btn('偿还债务','asset','secondary',`data-id="repay" ${minor?'disabled':''}`):''}</div><p class="hint">首付后新增贷款 48 万，每月自动还款。出售与继承时先结清债务。</p></section><section class="card asset-section"><div class="row"><h3>把家布置成喜欢的样子</h3>${icon('spark')}</div><div class="furniture-grid">${[['desk','book','一张书桌',1200],['sofa','home','舒适沙发',2400],['plants','flower','窗边绿植',200]].map(([id,ic,label,cost])=>`<button data-act="asset" data-id="${id}" ${minor||x.furniture.includes(id)?'disabled':''}><span>${icon(ic)}</span><strong>${label}</strong><small>${x.furniture.includes(id)?'已添置':'¥'+E.money(cost)}</small></button>`).join('')}</div><p class="hint">每添置一件物品，心情 +5。物品随当前角色保留。</p></section><section class="card asset-section"><div class="row"><span class="round-icon">${icon('briefcase')}</span><div class="flex"><h3>一间社区小店</h3><p>${x.business?`正在经营 ${x.business} 家小店`:'从一门小生意开始，积累家业。'}</p></div></div><p class="hint">每家启动资金 ¥50,000，月收益约 ¥300—1,900，受运气与经营波动影响。</p>${btn('投入 5万，开一家店','asset','secondary',`data-id="business" ${minor?'disabled':''}`)}</section>`;}
function family(){const x=p(),family=game.people.filter(q=>q.family),heirs=E.successors(game);return `${pageTitle('故事，比一生更长','家族的下一页',`<span class="pill">声望 ${game.familyReputation}</span>`)}<div class="family-intro card"><span class="round-icon">${icon('tree')}</span><div><h3>${esc(x.name[0])}氏家族 · 第${x.generation}代</h3><p>${family.length} 位家人，${family.filter(q=>q.alive).length} 人仍在续写故事。</p></div></div><div class="family-tree">${Array.from(new Set(family.map(q=>q.generation))).sort((a,b)=>a-b).map(gen=>`<section class="generation"><div class="generation-label">${gen===0?'原生家庭':'第 '+gen+' 代'}</div><div class="family-members">${family.filter(q=>q.generation===gen).map(q=>`<button class="family-member ${q.id===x.id?'current':''} ${q.alive?'':'past'}" data-act="person" data-id="${q.id}">${avatar(q)}<strong>${esc(q.name)}</strong><span>${q.id===x.id?'当前人生':esc(E.relationship(game,q))} · ${q.alive?ageText(q):'享年 '+Math.floor((q.died-q.born)/12)+'岁'}</span>${q.parents.length?`<small>${q.parents.map(id=>esc(game.people.find(z=>z.id===id)?.name)).join(' · ')}的孩子</small>`:''}</button>`).join('')}</div></section>`).join('')}</div><section class="card asset-section"><div class="row"><h3>下一代，新的可能</h3>${icon('spark')}</div><p>子女成年后，可以主动交班。上一代仍会继续生活，赠与和继承单独结算。</p>${heirs.length?heirs.map(q=>`<div class="heir-row">${avatar(q)}<div class="flex"><strong>${esc(q.name)}</strong><small>${ageText(q)} · ${esc(q.trait)}</small></div>${btn('由 TA 接班','confirm-handoff','secondary',`data-id="${q.id}"`)}</div>`).join(''):`<div class="empty-state small">${x.alive?'还没有可以接班的成年子女，先好好过眼前的生活。':'暂无可以接续的在世亲属。这一支家族的故事已完结，你可以在存档页开启新家族。'}</div>`}${x.alive&&x.spouse&&E.age(game)>=22&&E.age(game)<=55?btn('迎接一个孩子','confirm-baby','primary'):''}</section><p class="footnote">家族会传承资产、天赋倾向、人脉与共同经历。继承按游戏简化规则处理：资产折现、结清债务后，分给在世子女；无子女时由伴侣或父母承接。</p>`;}
function render(){if(screen==='create'){$('#app').innerHTML=creationScreen();return;}if(screen==='menu'){forceClose();$('#app').innerHTML=mainMenu();return;}if(!game){screen='menu';render();return;}save();if(O.isOpening(game)){renderOpening();return;}const contents={life,people,growth,assets,family};$('#app').innerHTML=`${header()}<div class="app-layout"><aside>${profile()}<div class="aside-note"><span class="eyebrow">这一生，由你慢慢写</span><p>不必每一步都有答案。<br>重要的是，那是你的选择。</p><div>第 ${game.time+1} 个月 ${icon('book')}</div></div></aside><div class="main-column">${nav()}${saveError?`<div class="error-note">${esc(saveError)}</div>`:''}<main id="main" class="page-enter ${guideStage()==='plan'?'guide-active':''}">${contents[view]()}</main><footer>人间续章 <span>·</span> 每一代，都有新的答案</footer></div></div>`;if(game.pending)showEvent();else if(guideStage()==='welcome')showWelcome();else if(guideStage()==='complete')showGuideComplete();}
function openModal(html,kind,required=false){modalKind=kind;const el=$('#modal');el.innerHTML=`<div class="modal-content">${required?'':`<button class="icon-button modal-close" data-act="close" aria-label="关闭">${icon('close')}</button>`}${html}</div>`;if(!el.open)el.showModal();el.dataset.required=String(required);}
function closeModal(){if($('#modal').dataset.required==='true')return;if(modalKind==='guide-welcome'){game.guide.stage='plan';forceClose();render();return;}if(modalKind==='guide-complete'){game.guide.stage='done';forceClose();render();return;}$('#modal').close();modalKind='';}
function forceClose(){$('#modal').close();$('#modal').dataset.required='false';modalKind='';}
function showEvent(){const ev=game.pending;if(!ev)return;openModal(`<div class="event-icon">${icon(ev.tag==='往事回响'?'chat':'spark')}</div><span class="eyebrow">${esc(ev.tag)} · ${ageText()}</span><h2 id="modal-title">${esc(ev.title)}</h2><p class="event-story">${esc(ev.text)}</p>${guideStage()==='event'?'<div class="guide-event-note">新手引导 · 第 3 步：读一读下面的结果，选一个你喜欢的回应。它会真实影响这段人生。<button class="guide-skip" data-act="guide-skip">跳过引导</button></div>':''}<div class="event-options">${ev.options.map((o,i)=>`<button data-act="event" data-id="${i}"><strong>${esc(o.label)}</strong><small>${esc(o.desc)}</small>${icon('chevron')}</button>`).join('')}</div><p class="hint">每一次选择，都会成为人生的一部分。</p>`,'event',true);}
function showPerson(id){const q=game.people.find(x=>x.id===id);if(!q)return;selectedPerson=id;const b=E.bond(game,game.active,id),self=q.id===game.active,canMarry=!self&&q.alive&&!q.family&&E.age(game)>=22&&!p().spouse&&!q.spouse;openModal(`<div class="person-modal-head">${avatar(q,'large')}<div><span class="eyebrow">${esc(E.relationship(game,q))} · ${q.alive?ageText(q):'留在记忆里'}</span><h2 id="modal-title">${esc(q.name)}</h2><p>${esc(q.trait)} · ${esc(q.job?.[0]||q.education)}</p></div></div><div class="profile-stats">${O.CORE.map(([k,label,tone])=>meter(label,q[k]??50,tone)).join('')}</div><p class="hint">个人存款 ¥${E.money(q.savings)}</p>${self?'':`<div class="growth-meters">${meter('亲密',b.closeness,'rose')}${meter('信任',b.trust,'blue')}</div>`}${q.alive&&!self&&!game.ended?`<div class="button-row">${btn('聊聊近况','interact','primary',`data-id="${id}" data-kind="talk"`)}${btn('给予帮助 ¥1,000','interact','secondary',`data-id="${id}" data-kind="help"`)}${canMarry?btn('结为伴侣','interact','secondary',`data-id="${id}" data-kind="marry"`):''}${q.family&&E.age(game)>=18?btn('赠与 ¥10,000','gift','secondary',`data-id="${id}"`):''}</div><p class="hint">聊天、帮助与结为伴侣各占用本月一次行动。结为伴侣需双方年满22岁，亲密70、信任55。</p>`:''}<h3 class="memory-heading">${self?'人生的重要时刻':'共同记忆'}</h3>${self?timeline(q.moments.slice(0,10)):b.memories.map(m=>`<div class="memory-item">${icon('chat')}<div><span class="meta">${Math.max(0,game.time-m.time)} 个月前</span><p>${esc(m.text)}</p></div></div>`).join('')||'<p class="muted">还没有共同记忆。一次认真回应，就是故事的开始。</p>'}${!q.alive?timeline(q.moments.slice(0,6)):''}`,'person');}
function settings(){openModal(`<span class="eyebrow">把故事好好保存</span><h2 id="modal-title">存档与设置</h2><p class="muted">存档保存在当前浏览器。更换设备前，请导出备份。</p><div class="save-slots">${db.slots.map((s,i)=>`<div class="save-slot ${i===db.current?'selected':''}"><div><span class="meta">家族档案 ${i+1}${i===db.current?' · 当前':''}</span><h3>${s?esc(E.active(s.game).name)+' · 第'+s.game.generation+'代':'空白档案'}</h3><small>${s?E.age(s.game)+'岁 · 已经历 '+s.game.time+' 个月':'开启一个新的家族故事'}</small></div>${s&&i===db.current&&screen==='game'?'<span class="blue">'+icon('check')+'</span>':btn(s?'读取':'新建','switch-slot','secondary',`data-id="${i}"`)}</div>`).join('')}</div><div class="button-row">${btn(icon('download')+'导出当前存档','export','secondary',game?'':'disabled')}${btn(icon('upload')+'导入备份','import','secondary')}</div><div class="button-row">${btn('重看新手引导','help','secondary')}${screen==='game'?btn('返回主菜单','menu','secondary'):''}</div>${game?'<button class="danger-link" data-act="confirm-new">重新开启当前档案</button>':''}<details class="rules"><summary>玩法与规则</summary><p>0—18岁每年完成一个成长事件；18岁决定是否参加考试与申请大学。成年后每个月有四次行动。安排完成后，点击「度过这个月」。行动可以重复，事件需要先作出选择才能继续。</p><p>每次选择后自动保存。关闭页面不会自动变老。成年后独立结算收支；大学期间可能获得家人支持。</p><p>子女成年后可交班。接班不转移财产，可先赠与；去世后资产折现并结清债务，剩余部分分配给继承人。</p><p>本作为架空的当代生活模拟，职业、升学、退休与资产规则均作游戏化简化。</p></details>`,'settings');}
function confirmation(title,text,label,act,id=''){openModal(`<span class="eyebrow">一个重要的决定</span><h2 id="modal-title">${esc(title)}</h2><p class="event-story">${esc(text)}</p><div class="button-row">${btn(label,act,'primary',`data-id="${esc(id)}"`)}${btn('再想想','close','secondary')}</div>`,'confirm');}
function run(fn,after){try{fn();forceClose();render();if(after)after();}catch(e){toast(e.message||'操作未完成，请重试');}}
document.addEventListener('click',e=>{const el=e.target.closest('[data-act]');if(!el||el.disabled)return;const act=el.dataset.act,id=el.dataset.id;if(el.tagName==='A')e.preventDefault();if(handleOpeningAction(act,id))return;if(handleMenuAction(act,id))return;if(screen!=='game'||!game)return;if(act==='nav'){view=id;render();window.scrollTo({top:0,behavior:'smooth'});}else if(act==='settings')settings();else if(act==='close')closeModal();else if(act==='plan')run(()=>E.setPlan(game,id));else if(act==='remove-plan')run(()=>{if(game.plan[Number(id)]==='talk')throw Error('已经完成的人物互动不能撤销');game.plan.splice(Number(id),1)});else if(act==='advance')run(()=>advanceMonth(),()=>{if(!game.pending)toast('新的一个月开始了');});else if(act==='event')run(()=>{E.resolveEvent(game,Number(id));if(guideStage()==='event')game.guide.stage='complete';});else if(act==='filter'){peopleFilter=id;render();}else if(act==='person')showPerson(id);else if(act==='interact')run(()=>E.interact(game,id,el.dataset.kind),()=>{showPerson(id);toast('这段经历已记在心里');});else if(act==='gift')confirmation('给予一份家庭支持',`将 ¥10,000 赠与${game.people.find(q=>q.id===id).name}，金额会从你的存款中扣除。`,'确认赠与','do-gift',id);else if(act==='do-gift')run(()=>E.gift(game,id),()=>toast('赠与已完成'));else if(act==='asset'){const texts={buyHome:['购入自己的家','支付 ¥120,000 首付，并承担 ¥480,000 住房贷款。'],sellHome:['出售一套住宅','以 ¥600,000 出售，所得优先清偿现有债务。'],business:['开一家社区小店','投入 ¥50,000，之后每月获得浮动经营收益。']};if(texts[id])confirmation(...texts[id],'确认','do-asset',id);else run(()=>E.assetAction(game,id),()=>toast('生活已更新'));}else if(act==='do-asset')run(()=>E.assetAction(game,id),()=>toast('资产已更新'));else if(act==='confirm-baby')confirmation('迎接下一代','一个新生命会带来陪伴与责任。未成年期间每月育儿开销增加 ¥700。','迎接孩子','baby');else if(act==='baby')run(()=>E.haveChild(game),()=>toast('家族迎来了一位新成员'));else if(act==='confirm-handoff')confirmation('续写下一章',`你将开始扮演${game.people.find(q=>q.id===id).name}。上一代继续生活，财产归属保留；本月未完成的安排将清空。`,'开始下一代人生','handoff',id);else if(act==='handoff')run(()=>{E.handoff(game,id);O.migrate(game);view='life'},()=>{window.scrollTo(0,0);toast('新的一章，从这里开始');});});
$('#modal').addEventListener('cancel',e=>{if($('#modal').dataset.required==='true'){e.preventDefault();return;}if(modalKind.startsWith('guide-')){e.preventDefault();closeModal();}});
let pendingImport=null;$('#import-file').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>5*1024*1024)throw Error('备份文件过大，请选择 5MB 以下的存档');const data=JSON.parse(await f.text());if(data.format!=='renjian-save')throw Error('请选择人间续章导出的 JSON 存档');pendingImport=O.validateOpening(E.validateGame(data.game));confirmation('恢复这份人生',`导入${E.active(pendingImport).name}的存档，将替换当前档案。`,'恢复存档','confirm-import');}catch(err){toast(err.message||'存档格式不正确');}});

function guideStage(){const stage=game?.guide?.stage;return ['welcome','plan','event','complete','done','skipped'].includes(stage)?stage:null;}
function mainMenu(){
  const x=game?E.active(game):null;
  return `<div class="title-screen"><header class="title-header"><span class="title-wordmark">${icon('book')}人生模拟器</span><span class="title-version">主菜单 · v0.3</span></header><main class="title-layout"><section class="title-intro"><span class="title-seal" aria-hidden="true">续</span><div class="title-kicker">LIFE, ONE CHAPTER AT A TIME</div><h1>人间<span>续章</span></h1><p class="title-subtitle">从一声啼哭，<br>到一个家族的故事。</p><div class="title-journey" aria-label="出生、成长、相遇、传承">${['出生','成长','相遇','传承'].map((label,i)=>`<span><i>${String(i+1).padStart(2,'0')}</i>${label}</span>`).join('')}</div></section><section class="menu-panel" aria-label="主菜单">${saveError?`<div class="error-note">${esc(saveError)}</div>`:''}${x?`<div class="last-life"><div class="eyebrow">上次的人生<span>档案 ${db.current+1}</span></div><div class="last-life-person">${avatar(x,'large')}<div><h2>${esc(x.name)}</h2><p>${ageText()} · 第 ${x.generation} 代</p></div><span class="pill">${esc(E.stage(game))}</span></div><p class="last-life-note">${game.pending?'还有一件人生事件，等你作出选择。':game.ended?'这一生已成故事，家族的下一章等你续写。':game.plan.length?`这个月已经安排了 ${game.plan.length} 次行动。`:'故事停在这里，等你回来。'}</p></div>`:`<div class="new-life-note"><span class="eyebrow">第一章 · 尚未落笔</span><h2>准备好，开始这一生。</h2><p>取一个名字，选两项特质。<br>用十八次选择，走到成年。</p></div>`}<div class="menu-main-actions">${x?btn(icon('book')+'继续人生','continue','primary menu-primary'):''}${btn(icon('plus')+'开启新人生','new-life',x?'secondary menu-secondary':'primary menu-primary')}<div class="menu-utilities">${btn(icon('wallet')+'存档管理','settings','menu-utility')}${btn(icon('spark')+'玩法说明','help','menu-utility')}</div></div><div class="menu-save-note">${icon('check')}自动保存 · 随时暂停 · 多代传承</div></section></main><footer class="title-footer"><span>一生很长，慢慢来。</span><span>存档保存在当前浏览器，可在存档管理中导出备份。</span></footer></div>`;
}
function selectNewLife(){
  openModal(`<span class="eyebrow">一段新的人生</span><h2 id="modal-title">为故事选一个位置</h2><p class="muted">选择空白档案开始。已有的人生会保留，只有明确确认后才会被替换。</p><div class="save-slots">${db.slots.map((s,i)=>`<div class="save-slot"><div><span class="meta">家族档案 ${i+1}</span><h3>${s?esc(E.active(s.game).name)+' · 第'+s.game.generation+'代':'空白档案'}</h3><small>${s?E.age(s.game)+'岁 · 已经历 '+s.game.time+' 个月':'取名、选特质，开始十八年的成长'}</small></div>${btn(s?'替换…':'从这里开始','choose-new-slot','secondary',`data-id="${i}"`)}</div>`).join('')}</div>`,'new-life');
}
let creation=null;
function newLifeAt(slot){
  if(!Number.isInteger(slot)||slot<0||slot>2)throw Error('请选择有效的档案位置');
  creation={slot,name:O.randomName(),traits:[]};screen='create';
}
function showWelcome(){
  openModal(`<span class="guide-step">新手引导 · 1 / 4</span><div class="guide-welcome-person">${avatar(p(),'large')}<div><span class="eyebrow">你的人生，从这里开始</span><h2 id="modal-title">你好，${esc(p().name)}。</h2></div></div><p class="event-story">成年后的生活按月推进。安排四次行动，再看看选择带来的变化。${p().flags.university?'你将在'+esc(p().flags.university)+'开启校园生活。':'你可以寻找工作、阅读进修，也可以结识新朋友。'}</p><div class="guide-stat-key">${O.CORE.map(([k,label])=>`<span><b>${label}</b>${Math.round(p()[k]??50)} / 100</span>`).join('')}</div><p class="guide-copy">接下来，亲手安排第一个月。只需要几步，随时可以跳过。</p><div class="button-row">${btn('带我开始','guide-start','primary')}${btn('跳过引导','guide-skip','secondary')}</div>`,'guide-welcome');
}
function guidePanel(){
  if(guideStage()!=='plan')return '';
  const full=game.plan.length===4;
  return `<section class="guide-panel" aria-label="新手引导"><div class="row"><span class="guide-step">新手引导 · 2 / 4</span>${btn('跳过引导','guide-skip','guide-skip')}</div><h3>${full?'安排好了，让第一个月开始。':'先为这个月安排四次行动。'}</h3><p>${full?'点击下面的「度过这个月」，看看你的选择带来了什么变化。':'点击下面喜欢的行动卡片，每点一次占一格。同一行动可以重复，已选安排也可以点掉。'}</p><div class="guide-progress" role="progressbar" aria-label="已安排的行动" aria-valuemin="0" aria-valuemax="4" aria-valuenow="${game.plan.length}">${Array.from({length:4},(_,i)=>`<i class="${i<game.plan.length?'filled':''}"></i>`).join('')}<span>${game.plan.length}/4</span></div><p class="guide-tip">第一次可以试试：学习、运动、陪伴和休息，各安排一次。</p></section>`;
}
function advanceMonth(){
  if(screen!=='game'||!game)throw Error('请先从主菜单进入人生');
  const guided=guideStage()==='plan';E.advance(game);
  if(guided&&!game.ended){
    game.guide.stage='event';
    if(!game.pending)game.pending={id:'first-month-guide',tag:'成长碎片',title:'成年生活的第一个月',text:'第一次自己安排生活，有忙碌，也有新的自由。你想怎样纪念这个开始？',options:[{label:'写下新的目标',desc:'智力 +2，心情 +2',effect:{ability:2,mood:2}},{label:'和家人分享近况',desc:'心情 +3',effect:{mood:3}}]};
  }
}
function showGuideComplete(){
  const d=game.summary?.deltas;
  openModal(`<span class="guide-step">新手引导 · 4 / 4</span><div class="guide-finish-icon">${icon('check')}</div><h2 id="modal-title">你已经走过第一个月。</h2><p class="guide-copy">安排、经历、选择，再看看自己有哪些变化。这就是人生继续向前的方式。</p>${d?`<div class="guide-result">${[['ability','智力'],['mood','心情'],['appearance','颜值']].map(([key,label])=>`<span>${label}<b>${signed(d[key]??0)}</b></span>`).join('')}</div><p class="hint">以上为行动结算变化，事件的结果也已记入人物状态。</p>`:''}<div class="guide-nav-key">${NAV.map(([id,ic,label])=>`<span>${icon(ic)}<b>${label}</b></span>`).join('')}</div><p class="guide-copy">在「人物」里认识家人，在「成长」里回看足迹。现在可以工作、恋爱与经营；子女成年后，可以接班。</p><div class="button-row">${btn('开始我的人生','guide-finish','primary')}${btn('再看一遍玩法','guide-review','secondary')}</div><p class="hint">进度已自动保存，退出页面不会自动变老。</p>`,'guide-complete');
}
const HELP=[
 ['为自己写下名字','book','开启新人生后，可以自填或随机名字，并选两个特质。卡片会说明特殊加成，四项核心属性为智力、运气、颜值、心情。'],
 ['十八个事件，走到成年','spark','0—18岁不再逐月安排。每一年有一个特殊事件，选择会影响四项属性。每次选择后自动保存，可以随时回到主菜单。'],
 ['十八岁，选择自己的路','award','可以参加或不参加考试。考试有15道简单选择题，每题50分，总分750；答题后看到解析。考试可中途保存，完成后按分数申请不同大学。'],
 ['成年后，按月经营生活','calendar','每月安排四次行动。智力影响学习与求职，运气影响际遇与经营，颜值影响约会，心情随经历变化。家人会记住相处，子女成年后可以接班。'],
 ['把故事好好保存','wallet','每次操作自动保存，提供三个家族档案。更换设备前请导出备份。旧版成年存档直接继续，未成年存档从当前年龄接入成长事件。']
];
function showHelp(step=0){
  step=Math.max(0,Math.min(HELP.length-1,Number(step)||0));const [title,ic,copy]=HELP[step];
  openModal(`<span class="guide-step">玩法说明 · ${step+1} / ${HELP.length}</span><div class="event-icon">${icon(ic)}</div><h2 id="modal-title">${title}</h2><p class="event-story">${copy}</p><div class="help-dots" aria-label="第${step+1}页，共${HELP.length}页">${HELP.map((_,i)=>`<i class="${i===step?'active':''}"></i>`).join('')}</div><div class="button-row">${step?btn('上一步','help-step','secondary',`data-id="${step-1}"`):''}${step<HELP.length-1?btn('下一步','help-step','primary',`data-id="${step+1}"`):btn('知道了','close','primary')}</div>`,'help');
}
function handleMenuAction(act,id){
  if(act==='menu'){if(screen!=='create')save();creation=null;screen='menu';forceClose();render();window.scrollTo(0,0);}
  else if(act==='continue'){if(game){O.migrate(game);screen='game';view='life';render();window.scrollTo(0,0);}}
  else if(act==='settings')settings();
  else if(act==='close')closeModal();
  else if(act==='help'||act==='help-step')showHelp(id);
  else if(act==='new-life')selectNewLife();
  else if(act==='choose-new-slot'){
    const slot=Number(id);if(!Number.isInteger(slot)||slot<0||slot>2)return true;
    if(db.slots[slot])confirmation('替换这段人生？',`档案 ${slot+1} 中${E.active(db.slots[slot].game).name}的进度将被替换。建议先在存档管理中导出备份。`,'确认替换并开始','start-new-slot',id);
    else run(()=>newLifeAt(slot));
  }
  else if(act==='start-new-slot')run(()=>newLifeAt(Number(id)));
  else if(act==='switch-slot')run(()=>{const slot=Number(id);if(!Number.isInteger(slot)||slot<0||slot>2)throw Error('请选择有效的档案');if(!db.slots[slot])newLifeAt(slot);else{save();db.current=slot;game=O.migrate(db.slots[slot].game);screen='game';view='life';}},()=>toast('已进入家族档案'));
  else if(act==='confirm-new')confirmation('重新开启这一份档案','当前档案将被新家族替换。建议先导出备份；其他档案不会受到影响。','重新开始','start-new-slot',String(db.current));
  else if(act==='confirm-import')run(()=>{if(!pendingImport)throw Error('请先选择备份文件');game=O.migrate(pendingImport);pendingImport=null;protectSave=false;screen='game';view='life';},()=>toast('备份已恢复'));
  else if(act==='guide-start')run(()=>{if(guideStage()==='welcome')game.guide.stage='plan';});
  else if(act==='guide-skip')run(()=>{if(game?.guide)game.guide.stage='skipped';});
  else if(act==='guide-finish')run(()=>{if(game?.guide)game.guide.stage='done';});
  else if(act==='guide-review')run(()=>{if(game?.guide)game.guide.stage='done';},()=>showHelp());
else if(act==='export'){const blob=new Blob([JSON.stringify({format:'renjian-save',version:1,game},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`人间续章_${p().name}_${ageText()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('存档备份已导出');}else if(act==='import')$('#import-file').click();
  else return false;
  return true;
}

function creationScreen(){
  const d=creation,stats={ability:30,luck:30,appearance:30,mood:60};
  d.traits.forEach(id=>{for(const [k,v] of Object.entries(O.TRAITS.find(t=>t.id===id).effect))stats[k]+=v;});
  return `${header()}<main class="creation-page page-enter"><div class="opening-heading"><span class="eyebrow">第一章 · 先认识你自己</span><h1>这一生，你想成为谁？</h1><p>写下名字，带着两份特别的天赋出发。</p></div><div class="creation-layout"><section class="card creation-form"><span class="section-number">01 / 你的名字</span><label for="character-name">家人将这样称呼你</label><div class="name-input-row"><input id="character-name" type="text" maxlength="24" autocomplete="off" value="${esc(d.name)}" placeholder="输入 1—12 个字的名字"><button data-act="random-name" class="secondary">${icon('spark')}随机取名</button></div><p class="hint">名字与两个特质确认后，这一生才会开始。</p><div class="row trait-heading"><span class="section-number">02 / 与生俱来的特质</span><span class="pill">已选 ${d.traits.length} / 2</span></div><div class="trait-picker">${O.TRAITS.map(t=>{const chosen=d.traits.includes(t.id);return `<button class="trait-choice ${chosen?'selected':''}" data-act="pick-trait" data-id="${t.id}" aria-pressed="${chosen}"><span class="trait-choice-top"><span class="round-icon">${icon(t.icon)}</span>${chosen?icon('check'):icon('plus')}</span><strong>${t.name}</strong><p>${t.desc}</p></button>`;}).join('')}</div></section><aside class="card creation-preview"><span class="eyebrow">你的人生起点</span><div class="preview-mark">初</div><h2 id="preview-name">${esc(d.name)||'尚未落笔'}</h2><p>四项核心属性 · 上限 100</p><div class="preview-stats">${O.CORE.map(([k,label,tone])=>meter(label,stats[k],tone)).join('')}</div><div class="creation-route"><span>01 <b>取名与特质</b></span><span>02 <b>十八次成长选择</b></span><span>03 <b>考试或走入社会</b></span></div><button class="primary create-submit" data-act="create-character" ${d.traits.length===2?'':'disabled'}>开启这一生 ${icon('chevron')}</button><p class="hint">保存到家族档案 ${d.slot+1} · 家庭出身随机</p></aside></div></main>`;
}
function openingResult(){const r=game.opening.last;return r?`<div class="year-result" role="status"><span class="result-check">${icon('check')}</span><div><strong>${r.age} 岁 · ${esc(r.choice)}</strong><p>${esc(O.effectsText(r.deltas))}${r.lucky?' · 触发幸运小事':''}</p></div></div>`:'';}
function renderOpening(){
  const o=game.opening;
  $('#app').innerHTML=`${header()}<div class="app-layout opening-layout"><aside>${profile()}<div class="aside-note"><span class="eyebrow">十八次选择，长成你自己</span><p>出生只是起点。<br>接下来的故事，由你来写。</p></div></aside><main class="main-column opening-main page-enter">${openingContent()}<details class="history opening-history"><summary>回看成长足迹</summary>${timeline(game.logs.filter(l=>l.person===game.active).slice(0,24))}</details><footer>选择后自动保存 <span>·</span> 随时可以回到主菜单</footer></main></div>`;
  if(game.pending)showEvent();
}
function openingContent(){
 const o=game.opening;
 if(o.phase==='childhood'){
  const ev=O.CHILDHOOD[o.index];
  return `${pageTitle('成长序章 · 0—18 岁','把十八年，写成十八个瞬间',`<span class="pill">${o.index} / 18 已完成</span>`)}${o.intro?`<div class="guide-panel"><div class="row"><span class="guide-step">新手引导 · 成长篇</span>${btn('收起提示','opening-help-off','text-button')}</div><h3>每次选择，长大一岁。</h3><p>选项下方会显示属性变化。18个事件后，你将决定是否参加考试。${o.legacy?'这是旧存档，已保留你的名字、属性和家人，从当前年龄继续。':'家庭出身已经确定：'+esc(game.origin)+'。'}</p></div>`:''}${openingResult()}<section class="card childhood-card"><div class="childhood-progress" aria-label="成长进度">${Array.from({length:18},(_,i)=>`<i class="${i<o.index?'done':i===o.index?'current':''}"></i>`).join('')}</div><div class="year-label"><span>第 ${String(o.index+1).padStart(2,'0')} 个成长事件</span><b>${o.index}<small> → </small>${o.index+1}<small> 岁</small></b></div><span class="event-kicker">${esc(E.stage(game))}</span><h2>${ev.title}</h2><p class="event-story">${ev.text}</p><div class="event-options childhood-options">${ev.options.map((op,i)=>`<button data-act="child-choice" data-id="${i}" ${game.pending?'disabled':''}><span class="option-letter">${String.fromCharCode(65+i)}</span><span><strong>${op.label}</strong><small>${O.effectsText(op.effect)}</small></span>${icon('chevron')}</button>`).join('')}</div><p class="hint">${p().startTraits.includes('sunny')?'天生乐天：每次选择额外心情 +1。 ':''}运气越高，越容易遇到带来心情 +2、运气 +1 的幸运小事。</p></section>`;
 }
 if(o.phase==='choice')return `${pageTitle('成长序章 · 完成','十八岁，人生开始由你做主')} ${openingResult()}<section class="card adulthood-card"><span class="milestone-number">18<small>岁</small></span><h2>带着这些年的成长，走向远方。</h2><p class="event-story">${esc(p().name)}，你已走过童年和少年。现在的四项属性，就是成年生活的起点。你想先去大学看看，还是直接进入社会？</p><div class="adult-initial">${O.CORE.map(([k,l])=>`<span>${l}<strong>${Math.round(p()[k])}</strong></span>`).join('')}</div><div class="path-cards"><button data-act="start-exam" class="path-card"><span class="round-icon">${icon('book')}</span><strong>参加考试</strong><p>15 道简单题 · 每题 50 分<br>满分 750，按分数申请大学</p><span class="blue">看看自己能得多少分 →</span></button><button data-act="skip-exam" class="path-card"><span class="round-icon">${icon('briefcase')}</span><strong>不参加考试</strong><p>直接开始成年生活<br>寻找工作、学习与结识朋友</p><span class="blue">走出自己的另一条路 →</span></button></div><p class="hint">考试无时间限制，可中途退出并继续；开始后需完成本次答卷。题目得分只取决于答案，不受属性加成影响。</p></section>`;
 if(o.phase==='exam'){
  const x=o.exam,entry=x.paper[x.cursor],q=O.QUESTIONS[entry.id],answered=x.answers.length>x.cursor,answer=x.answers[x.cursor],correct=answered&&entry.options[answer]===0;
  return `${pageTitle('十八岁的考试','给未来，交一份自己的答卷',`<span class="pill">${x.cursor+1} / 15 题</span>`)}<section class="card exam-card"><div class="exam-meta"><span>答对一题 +50 分</span><strong>${O.examScore(game)}<small> / 750</small></strong></div><div class="exam-progress"><i style="width:${x.answers.length/15*100}%"></i></div><span class="event-kicker">第 ${String(x.cursor+1).padStart(2,'0')} 题 · 单选</span><h2>${q[0]}</h2><div class="exam-options">${entry.options.map((v,i)=>`<button data-act="exam-answer" data-id="${i}" ${answered?'disabled':''} class="${answered&&v===0?'correct':answered&&i===answer?'wrong':''}"><span class="option-letter">${String.fromCharCode(65+i)}</span><strong>${q[1][v]}</strong>${answered&&v===0?icon('check'):''}</button>`).join('')}</div>${answered?`<div class="answer-feedback ${correct?'correct':'wrong'}" role="status"><strong>${correct?'答对了！+50 分':'这题答错了，本题 0 分'}</strong><p>${q[2]}</p></div>${btn(x.cursor===14?'查看成绩与大学':'下一题','exam-next','primary exam-next')}`:'<p class="hint">点击答案即提交，提交后可查看解析。进度会自动保存。</p>'}</section>`;
 }
 const score=O.examScore(game);
 return `${pageTitle('考试完成 · 大学申请','下一站，去哪里？')}<section class="card score-card"><span class="eyebrow">你的考试成绩</span><strong>${score}<small> / 750</small></strong><p>答对 ${score/50} 题 / 共 15 题</p><span class="pill">${score>=650?'向更远处出发':score>=150?'你的选择，正在展开':'分数之外，还有许多可能'}</span></section><p class="university-note">达到要求即可申请录取，选择一次后进入成年生活。学校与分数线均为游戏设定。</p><div class="university-list">${O.UNIVERSITIES.map(u=>`<section class="card university-card ${score<u.min?'locked':''}"><div class="row"><span class="tag">${u.tag} · ${u.years} 年</span><span class="threshold">${u.min} 分起</span></div><h3>${u.name}</h3><p>${u.desc}</p>${btn(score>=u.min?'申请入学':'还差 '+(u.min-score)+' 分','apply-university',score>=u.min?'primary':'secondary',`data-id="${u.id}" ${score<u.min?'disabled':''}`)}</section>`).join('')}</div><div class="card alternative-path"><div><h3>暂不入学，也可以继续出发。</h3><p>保留成绩记录，直接进入按月安排的成年生活。</p></div>${btn('直接进入社会','skip-exam','secondary')}</div><details class="history"><summary>回顾答卷与解析</summary>${o.exam.paper.map((entry,i)=>{const q=O.QUESTIONS[entry.id];return `<article class="answer-review"><strong>${i+1}. ${q[0]}</strong><p>你的答案：${q[1][entry.options[o.exam.answers[i]]]} · ${entry.options[o.exam.answers[i]]===0?'50 分':'0 分'}</p><small>${q[2]}</small></article>`;}).join('')}</details>`;
}
function handleOpeningAction(act,id){
 if(act==='random-name'&&creation){creation.name=O.randomName();render();}
 else if(act==='pick-trait'&&creation){if(!O.TRAITS.some(t=>t.id===id))return true;if(creation.traits.includes(id))creation.traits=creation.traits.filter(t=>t!==id);else if(creation.traits.length<2)creation.traits.push(id);else{toast('已选两个特质，请先取消一个');return true;}render();}
 else if(act==='create-character'&&creation)run(()=>{const created=O.createLife(creation.name,creation.traits);save();db.current=creation.slot;game=created;creation=null;protectSave=false;screen='game';view='life';window.scrollTo(0,0);});
 else if(screen==='game'&&O.isOpening(game)){
  if(act==='child-choice')run(()=>O.chooseChildhood(game,Number(id)));
  else if(act==='opening-help-off')run(()=>{game.opening.intro=false;});
  else if(act==='start-exam')run(()=>{O.startExam(game);window.scrollTo(0,0);});
  else if(act==='exam-answer')run(()=>O.answerExam(game,Number(id)));
  else if(act==='exam-next')run(()=>{O.nextQuestion(game);window.scrollTo(0,0);});
  else if(act==='apply-university'){const u=O.UNIVERSITIES.find(u=>u.id===id);if(u)confirmation('申请'+u.name,`以 ${O.examScore(game)} 分申请${u.name}，录取后进入${u.years}年的校园生活。`,'确认入学','confirm-university',id);}
  else if(act==='confirm-university')run(()=>O.enterAdult(game,id));
  else if(act==='skip-exam')confirmation(game.opening.phase==='choice'?'不参加这次考试？':'暂不申请大学？','确认后直接进入成年生活，开始按月安排。这一轮成长中的升学选择将结束。','进入社会','confirm-society');
  else if(act==='confirm-society')run(()=>O.enterAdult(game));
  else return false;
 }else return false;
 return true;
}
document.addEventListener('input',e=>{if(e.target.id==='character-name'&&creation){creation.name=e.target.value;const preview=$('#preview-name');if(preview)preview.textContent=creation.name||'尚未落笔';}});

render();
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();const registration=[{name:'read_life_state',description:'Read the active life, monthly action choices and pending event without advancing time.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>game?({screen,name:p().name,age:E.age(game),month:game.time,generation:game.generation,plan:game.plan,actions:E.actions(game).map(a=>({id:a.id,name:a.name})),pending:game.pending,ended:game.ended}):({screen:'menu',hasSave:false})},{name:'set_monthly_plan',description:'Replace the four monthly action slots. Does not advance time. Completed person interactions cannot be replaced.',inputSchema:{type:'object',properties:{actions:{type:'array',items:{type:'string'},minItems:4,maxItems:4}},required:['actions'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(screen!=='game'||!game||!input||!Array.isArray(input.actions)||input.actions.length!==4||game.pending||game.ended||game.plan.includes('talk')||input.actions.some(id=>!E.actions(game).some(a=>a.id===id)))throw Error('Invalid plan or pending event');game.plan=[...input.actions];render();return{plan:game.plan};}},{name:'advance_life_one_month',description:'Complete the staged four actions and advance this life by exactly one month. May present a pending event.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:()=>{advanceMonth();render();return{month:game.time,pending:game.pending,ended:game.ended};}}];for(const tool of registration){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
