import assert from 'node:assert/strict';
import * as E from '../engine.js?v=0.3';
import * as O from '../opening.js?v=0.3';
const create=()=>O.createLife('林知夏',['bright','sunny'],1234);
const grow=g=>{for(let i=0;i<18;i++)O.chooseChildhood(g,i%2);return g;};
const exam=(g,n)=>{O.startExam(g);for(let i=0;i<15;i++){const q=g.opening.exam.paper[i];O.answerExam(g,q.options.indexOf(i<n?0:1));O.nextQuestion(g);}return g;};
let g=create();assert.equal(E.active(g).name,'林知夏');assert.equal(E.active(g).ability,38);assert.equal(E.active(g).mood,68);assert.equal(E.active(g).luck,30);assert.equal(E.active(g).appearance,30);
assert.throws(()=>O.createLife(' ',['bright','sunny']));assert.throws(()=>O.createLife('小林',['bright','bright']));assert.throws(()=>O.createLife('小林',['unknown','sunny']));assert.throws(()=>E.setPlan(g,'rest'));assert.throws(()=>E.advance(g));assert.equal(O.CHILDHOOD.length,18);assert.equal(new Set(O.CHILDHOOD.map(e=>e.title)).size,18);
const parent=structuredClone(g.people[0]);for(let i=0;i<18;i++){const previous=g.time;O.chooseChildhood(g,i%2);assert.equal(g.time-previous,12);assert.equal(E.age(g),i+1);O.validateOpening(E.validateGame(g));}
assert.equal(g.opening.phase,'choice');assert.equal(g.opening.history.length,18);assert.equal(E.age(g,g.people[0]),Math.floor(-parent.born/12)+18);assert.throws(()=>O.chooseChildhood(g,0));assert.equal(E.active(g).flags.examScore,undefined,'No automatic/random exam score');assert.throws(()=>O.enterAdult(g,'xinghe'));
O.startExam(g);const q=g.opening.exam.paper[0];O.answerExam(g,q.options.indexOf(0));assert.equal(O.examScore(g),50);assert.throws(()=>O.answerExam(g,0),'Duplicate answer blocked');
let restored=O.validateOpening(E.validateGame(JSON.parse(JSON.stringify(g))));assert.deepEqual(restored,g);O.nextQuestion(restored);assert.equal(restored.opening.exam.cursor,1);assert.throws(()=>O.nextQuestion(restored));
const broken=structuredClone(restored);broken.opening.exam.paper[1].id=broken.opening.exam.paper[0].id;assert.throws(()=>O.validateOpening(broken));
for(const count of [0,2,3,6,7,9,10,12,13,15]){const x=exam(grow(create()),count);assert.equal(O.examScore(x),count*50);assert.equal(E.active(x).flags.examScore,count*50);assert.equal(x.opening.phase,'result');assert.throws(()=>O.answerExam(x,0));for(const u of O.UNIVERSITIES){const y=structuredClone(x);if(count*50<u.min)assert.throws(()=>O.enterAdult(y,u.id));else{O.enterAdult(y,u.id);assert.equal(E.active(y).education,u.type);assert.equal(y.opening.phase,'adult');}}O.validateOpening(E.validateGame(x));}
const skip=grow(create());O.enterAdult(skip);assert.equal(skip.opening.phase,'adult');assert.equal(E.active(skip).flags.skippedExam,true);assert.equal(E.active(skip).education,'高中毕业');assert.equal(E.active(skip).flags.examScore,undefined);
const admitted=exam(grow(create()),15);O.enterAdult(admitted,'xinghe');const initialName=E.active(admitted).name;while(E.age(admitted)<22){for(const a of ['study','exercise','family','rest'])E.setPlan(admitted,a);E.advance(admitted);if(admitted.pending)E.resolveEvent(admitted,0);}assert.equal(E.active(admitted).education,'本科');assert.equal(E.active(admitted).name,initialName);assert.equal(E.active(admitted).flags.examScore,750);assert.ok(E.active(admitted).moments.some(m=>m.title==='毕业快乐'));
const legacy=E.newGame(12);legacy.time=12*8+3;const ability=E.active(legacy).ability,name=E.active(legacy).name;O.migrate(legacy);assert.equal(legacy.opening.index,8);O.chooseChildhood(legacy,0);assert.equal(E.age(legacy),9);assert.equal(E.active(legacy).name,name);assert.ok(E.active(legacy).ability>=ability);O.validateOpening(E.validateGame(legacy));
const before=O.createLife('测试',['bright','sunny'],50);const after=structuredClone(before);O.chooseChildhood(before,1);O.chooseChildhood(after,1);assert.deepEqual(before,after,'Save resumes RNG and childhood effects deterministically');
console.log('PASS: creation, trait bonuses, 18 unique annual events, 0–750 scores, university cutoffs, skip, graduation, save resume and migration');
